version: 2.1

jobs:
  build_api:
    docker:
      - image: 'cimg/node:current'
    steps:
      - checkout
      - run:
          command: npm install

workflows:
  version: 2
  my_workflow_for_currecy:
    jobs:
      - build_api
